### ISSUE TITLE
关于单个字符的实体

### ISSUE THREAD

**Issue by ssnvxia** [ssnvxia/OneRel#1]
最近收到一些小伙伴的邮件，主要问题集中在“目前的标注方式在头实体或者尾实体只有一个字符的时候会出问题”。在此详细解释。

首先，上述标注方式在处理单个字符实体的时候是不矛盾的。因为我们是按照HB-TB，HB-TE，HE-TE的顺序来标注实体边界，单个字符实体的后一个标签会覆盖掉之前的标签。因此，如果是头实体单个字符，尾实体多个字符，则解码时查询HB-TB与HB-TE组成的元组即可；如果头实体和尾实体都只有一个字符，则在解码过程中查询孤立的HE-TE即可。这种方法是可行的，但是比较麻烦。

因此，我们在实现过程中，采用了“将句子中的空格也作为字符”的方式，即“北京今天有雨”会被tokenize成“北[u]京[u]今[u]天[u]有[u]雨[u]”，话相当于每一个字符都是由它本身和之后的空格组成，也就不存在单个字符组成的实体的情况。这样做会使句子长度变成原来的两倍，明显降低模型运行速度（从约60ms一个batch到约140ms一个batch），但是能简化模型在推理阶段的逻辑。

**Comment by pcx-pcx** [comment]
也可以多加一个标签S（当实体为单字符时的标签），这样实体的标签可以为B、I、E、S，那最后三元组的识别就可扩展到了四种情况：HB-TB->HB-TE->HE-TE(主客体字符数都大于1的情况)、HB-TS->HE-TS(主>1,客=1)、HS-TB->HS-TE(主=1,客>1)、HS-TS(主=1，客=1)

**Comment by jie74** [comment]
@pcx-pcx
如果有实体嵌套的话还是会出现问题。例如实体“insulin”和“insulin receptor”，那“insulin”(假设主体)的地方应该标注HB还是HS。还是论文作者的[unused]可解决情况多，而且标签类别越简单通常越好。
