### ISSUE TITLE
关于结果的疑问

### ISSUE THREAD

**Issue by 2azhui** [ssnvxia/OneRel#12]
作者您好！我想问一下 为什么您提供的webNLG的模型 在验证集的效果却不如测试集的效果呢？

**Comment by ssnvxia** [comment]
您好，验证集的目的是为了调参，即在当时设置的参数范围内，选择验证集上效果最好的模型用于测试。我理解二者之间的效果没有必然联系吧。即有可能在验证集上的绝对F1比在测试集上高，也有可能比在测试集上低。

**Comment by ssnvxia** [comment]
您好，感谢您的提问！
模型在测试集和验证集上的效果是没有关联的。可能验证集高一点，也可能测试集高一点，与具体的数据分布有关。

如果直接在验证集上调参到最优效果，而后测试，那么大概率得到的是一个在验证集上过拟合的模型，而测试集的效果则会差的比较多。

在发布的代码中这样写，是为了方便使用者的训练和测试。
在实际调参过程中，我们关注模型在验证集上效果的变化，在过拟合之前便会停止训练。

**Comment by 2azhui** [comment]
那论文里的数据是测试集的还是验证集的？

**Comment by ssnvxia** [comment]
论文里的数据是在测试集上的结果~如果您有什么疑问或者需要探讨的地方，欢迎邮件联系~~
