### ISSUE TITLE
感谢分享，提一个关于我训练过慢的疑问

### ISSUE THREAD

**Issue by zphhhhh** [ssnvxia/OneRel#2]
感谢作者分享的代码，效果很好。但在训练过程中稍微有点慢，如果要把在 tokenize 时候添加的空格去掉，该如何解码呢？能否提供相应的代码？再次感谢！

**Comment by ssnvxia** [comment]
您好，解码的思路就是后一个标签会覆盖前一个标签，然后再表格中分类讨论，寻找对应的标签对。
由于我最近较忙，在之后有空会补充这部分代码。
短期内建议您自己实现一下。
感谢您对我工作的关注。
