### ISSUE TITLE
请教在其他数据集发生的一个错误

### ISSUE THREAD

**Issue by Yuknoshita** [ssnvxia/OneRel#3]
感谢您分享的代码。
我在三个生物数据集上做了测试，数据集都是采取您data中nyt相同的输入格式，且之前**都可以在casrel上运行测试**。但是在onerel上，只有其中一个可以训练完毕，其他都会在第一轮运行到某个batch时出现这个错误：

> `Original Traceback (most recent call last):
  File "/home/E20201038/conda_envs/one/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/E20201038/conda_envs/one/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/home/E20201038/onerel/data_loader.py", line 106, in re_collate_fn
    token_ids, masks, loss_masks, text_len, triple_matrix, triples, tokens = zip(*batch)
ValueError: not enough values to unpack (expected 7, got 0)`

错误代码位于data_loader()的()re_collate_fn(batch):

> `    token_ids, masks, loss_masks, text_len, triple_matrix, triples, tokens = zip(*batch)`

我已经按照您readme上的要求修改了batch_triple_matrix和rel_num, 是您的代码对某些输入数据有要求吗？感谢您的赐教。

**Comment by ssnvxia** [comment]
您好，看到报错的意思大概是因为  代码默认batch中包含了token_ids等7个数据，可是您实际放入batch中的数据少于7个。所以请您检查一下组装batch的过程，看看是否哪里漏掉了什么数据，或者是把不需要的数据从上述代码中删掉即可。

**Comment by Yuknoshita** [comment]
好的，感谢您的回复



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月15日(星期五) 中午11:10
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ssnvxia/OneRel] 请教在其他数据集发生的一个错误 (Issue #3)





 
您好，看到报错的意思大概是因为  代码默认batch中包含了token_ids等7个数据，可是您实际放入batch中的数据少于7个。所以请您检查一下组装batch的过程，看看是否哪里漏掉了什么数据，或者是把不需要的数据从上述代码中删掉即可。

**Comment by jielunzhou18754** [comment]
我也遇到了这个情况 在自己的数据集上遇到的 ，数据集是中文的也换成了chinese_bert_base 在casrel是数据集可以正常运行但是在这个情况下不能 是分词器的原因吗？

**Comment by Yun-Peng-Wang** [comment]
> 感谢您分享的代码。 我在三个生物数据集上做了测试，数据集都是采取您data中nyt相同的输入格式，且之前**都可以在casrel上运行测试**。但是在onerel上，只有其中一个可以训练完毕，其他都会在第一轮运行到某个batch时出现这个错误：
> 
> > `Original Traceback (most recent call last):   File "/home/E20201038/conda_envs/one/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop     data = fetcher.fetch(index)   File "/home/E20201038/conda_envs/one/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch     return self.collate_fn(data)   File "/home/E20201038/onerel/data_loader.py", line 106, in re_collate_fn     token_ids, masks, loss_masks, text_len, triple_matrix, triples, tokens = zip(*batch) ValueError: not enough values to unpack (expected 7, got 0)`
> 
> 错误代码位于data_loader()的()re_collate_fn(batch):
> 
> > `    token_ids, masks, loss_masks, text_len, triple_matrix, triples, tokens = zip(*batch)`
> 
> 我已经按照您readme上的要求修改了batch_triple_matrix和rel_num, 是您的代码对某些输入数据有要求吗？感谢您的赐教。

我在中文数据集是直接报这个错，是这个原版不能在中文数据集上运行吗
