### ISSUE TITLE
关于环境变量的问题

### ISSUE THREAD

**Issue by guanxichouqu** [ssnvxia/OneRel#7]
你好，我想问一下环境变量的设置问题，我老是cuda与torch版本不匹配问题 谢谢啦

**Comment by ssnvxia** [comment]
您好，建议按照如下步骤进行
1. 安装anaconda
2. 在pytorch官网，点击install
3. 选择linux, conda, 自己的cuda版本
4. 将命令复制到命令行中，运行，等待就好
