### ISSUE TITLE
输出F1值为什么是0？

### ISSUE THREAD

**Issue by sdnunier** [ssnvxia/OneRel#9]
输出F1值为什么是0？

**Comment by ssnvxia** [comment]
抱歉，您的这个问题我没有遇到过。我猜测可能是以下两个原因：
1. 训练的迭代次数较少，模型完全没有收敛，这种情况多跑几个epoch再看看。
2. 是否不小心修改了输出的的相关代码，导致模型评价指标计算出现问题。

**Comment by sdnunier** [comment]
谢谢！   我还有一个问题   为什么projection矩阵的输出维度要设为bertdim*3
